### ISSUE TITLE
Nombre de la Propiedad id_calificacion ó Calificación_id

### ISSUE THREAD

**Issue by Juanflugel** [lasdjs/docs#1]
http://localhost:3001/#Mod-docente-contenido & http://localhost:3001/#Mod-docente-notas
![image](https://cloud.githubusercontent.com/assets/9297847/6739568/bb35b6e8-ce79-11e4-98b5-1bee0329ddca.png)

![image](https://cloud.githubusercontent.com/assets/9297847/6739596/ebe8e2a6-ce79-11e4-88b8-80c4210074a5.png)

**Comment by lasdjs** [comment]
Estandaricemos, cual seria si id_foo, idfoo, foo_id o fooid ?.
Voto por id_foo

**Comment by Newville23** [comment]
voy con id_foo

**Comment by lasdjs** [comment]
Listo
